version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 02ms1m@x!
      POSTGRES_DB: time2caredb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run start:dev
    depends_on:
      - postgres

volumes:
  postgres_data:
