name: time2care
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data
      - ./caddy-config:/config
    depends_on:
      - backend
    networks: [web]

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: H7w9Zf4uN6r5Q0x2L3m8Y1p
      POSTGRES_DB: time2caredb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d time2caredb']
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [web]

  backend:
    build: .
    env_file: [.env]
    restart: unless-stopped
    expose:
      - '3000' # only for the proxy, not the internet
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks: [web]

networks:
  web:

volumes:
  postgres_data:
  uploads_data:
